import type { ElementData } from '../../types.ts';

/** Default computed styles that satisfy all rule requirements with no-op-free values. */
export const DEFAULT_COMPUTED_STYLES: ElementData['computedStyles'] = {
  display: 'block',
  width: 'auto',
  height: 'auto',
  gap: 'normal',
  rowGap: 'normal',
  columnGap: 'normal',
  alignContent: 'normal',
  alignItems: 'normal',
  justifyContent: 'normal',
  justifyItems: 'normal',
  placeItems: 'normal',
  placeContent: 'normal',
  columnCount: 'auto',
  columnFill: 'balance',
  columnRuleStyle: 'none',
  columnRuleWidth: '0px',
  columnWidth: 'auto',
  position: 'static',
  top: 'auto',
  right: 'auto',
  bottom: 'auto',
  left: 'auto',
  insetBlockStart: 'auto',
  insetBlockEnd: 'auto',
  insetInlineStart: 'auto',
  insetInlineEnd: 'auto',
  alignSelf: 'auto',
  justifySelf: 'auto',
  order: '0',
  marginTop: '0px',
  marginBottom: '0px',
  marginBlockStart: '0px',
  marginBlockEnd: '0px',
  verticalAlign: 'baseline',
  zIndex: 'auto',
  opacity: '1',
  transform: 'none',
  filter: 'none',
  backdropFilter: 'none',
  perspective: 'none',
  clipPath: 'none',
  isolation: 'auto',
  mixBlendMode: 'normal',
  mask: 'none',
  containerType: 'normal',
  contain: 'none',
  willChange: 'auto',
  flexDirection: 'row',
  flexWrap: 'nowrap',
  flexGrow: '0',
  flexShrink: '1',
  flexBasis: 'auto',
  cssFloat: 'none',
  gridTemplateColumns: 'none',
  gridTemplateRows: 'none',
  gridTemplateAreas: 'none',
  gridAutoColumns: 'auto',
  gridAutoRows: 'auto',
  gridAutoFlow: 'row',
  gridColumnStart: 'auto',
  gridColumnEnd: 'auto',
  gridRowStart: 'auto',
  gridRowEnd: 'auto',
  textOverflow: 'clip',
  overflowX: 'visible',
  overflowY: 'visible',
  resize: 'none',
  inlineSize: 'auto',
  blockSize: 'auto',
  minInlineSize: '0px',
  maxInlineSize: 'none',
  minBlockSize: '0px',
  maxBlockSize: 'none',
  minWidth: '0px',
  maxWidth: 'none',
  minHeight: '0px',
  maxHeight: 'none',
  aspectRatio: 'auto',
  objectFit: 'fill',
  objectPosition: '50% 50%',
  shapeOutside: 'none',
  shapeMargin: '0px',
  shapeImageThreshold: '0',
  clear: 'none',
  textIndent: '0px',
  rotate: 'none',
  scale: 'none',
  offsetPath: 'none',
  animationName: 'none',
  animationDuration: '0s',
  animationTimingFunction: 'ease',
  animationDelay: '0s',
  animationIterationCount: '1',
  animationDirection: 'normal',
  animationFillMode: 'none',
  animationPlayState: 'running',
  marginRight: '0px',
  marginLeft: '0px',
  paddingTop: '0px',
  paddingRight: '0px',
  paddingBottom: '0px',
  paddingLeft: '0px',
  borderTopWidth: '0px',
  borderRightWidth: '0px',
  borderBottomWidth: '0px',
  borderLeftWidth: '0px',
  marginInlineStart: '0px',
  marginInlineEnd: '0px',
  paddingBlockStart: '0px',
  paddingBlockEnd: '0px',
  paddingInlineStart: '0px',
  paddingInlineEnd: '0px',
  borderBlockStartWidth: '0px',
  borderBlockEndWidth: '0px',
  borderInlineStartWidth: '0px',
  borderInlineEndWidth: '0px',
  backgroundColor: 'rgba(0, 0, 0, 0)',
  backgroundImage: 'none',
  outlineStyle: 'none',
  scrollPaddingTop: 'auto',
  scrollPaddingRight: 'auto',
  scrollPaddingBottom: 'auto',
  scrollPaddingLeft: 'auto',
  scrollPaddingBlockStart: 'auto',
  scrollPaddingBlockEnd: 'auto',
  scrollPaddingInlineStart: 'auto',
  scrollPaddingInlineEnd: 'auto',
  scrollSnapAlign: 'none',
  scrollSnapStop: 'normal',
  writingMode: 'horizontal-tb',
  boxSizing: 'content-box',
  borderCollapse: 'separate',
  borderSpacing: '0px 0px',
  emptyCells: 'show',
  tableLayout: 'auto',
};

/** Create a test ElementData with overrides and optional tagName / parent. */
export function makeElement(
  overrides: Partial<ElementData['computedStyles']> & { tagName?: string } = {},
  parent: ElementData['parent'] = null,
  inlineStyles?: Record<string, string>,
): ElementData {
  const { tagName = 'div', ...styles } = overrides;
  const computedStyles: Record<string, string> = { ...DEFAULT_COMPUTED_STYLES };
  for (const [key, value] of Object.entries(styles)) {
    if (value !== undefined) computedStyles[key] = value;
  }
  const el: ElementData = { tagName, id: '', classList: [], computedStyles, parent };
  if (inlineStyles) el.inlineStyles = inlineStyles;
  return el;
}

const DEFAULT_BLOCK_PARENT: ElementData['parent'] = { computedStyles: { display: 'block' } };

/** Like makeElement, but defaults parent to a block container instead of null. */
export function makeChildElement(
  styles: Partial<ElementData['computedStyles']>,
  parent: ElementData['parent'] = DEFAULT_BLOCK_PARENT,
): ElementData {
  return makeElement(styles, parent);
}
